### ISSUE TITLE
[FEATURE] Enhance.com & ISPVMManager

### ISSUE THREAD

**Issue by ghost** [Paymenter/Extensions#16] opened 2023-06-07 04:31 UTC
Intergration with https://enhance.com | https://apidocs.enhance.com/
as well as intergration with https://www.ispsystem.com/vmmanager | https://docs.ispsystem.com/vmmanager-admin/developer-section/api/vmmanager-api

**Comment by CorwinDev** [comment] 2023-10-11 06:47
Enhance.com: ✔️

**Comment by Pachini** [comment] 2024-02-25 19:09
@CorwinDev thank you for the integration with "Enhance"! But there is an important point, after payment the user does not receive an email with password or any data about "enhance" at all.  Because "enhance" doesn't have a "welcome email" with login data. And "Paymenter" doesn't do that either. Also from the order it is not possible to go to the enhancement panel, as for example it is realized in virtfustion integration.

Below is the response of "enhance" support:

"Enhance does not send welcome emails. Normally the billing platform would do this. I don't know if Paymenter sends these emails, you would need to ask their team. 

There is also an SSO function which can be used to log a customer in to their panel without needing separate credentials but again the Paymenter team would need to integrate this."

**Comment by CorwinDev** [comment] 2024-02-26 10:27
Hi @Pachini i'll include this feature very soon!

**Comment by CorwinDev** [comment] 2024-02-26 10:49
@Pachini just added this feature, please redownload enhance from <yourDomain>/admin/extensions/browse and let me know if it works intended :)

**Comment by Pachini** [comment] 2024-02-26 13:05
@CorwinDev, awesome, thank you! But I encountered a couple of problems, I solved the first one, the second one solved itself

1. Incorrect file extension location: The Enhance.php.php file is located at **Extensions/Enhance/Enhance/Enhance.php**. However, it should be **Extensions/Enhance/Enhance.php**.

I encountered an error until I moved the file to the upper folder:

`[2024-02-26 11:18:11] production.ERROR: include(/var/www/paymenter/vendor/composer/../../app/Extensions/Servers/Enhance/Enhance.php): failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): include(/var/www/paymenter/vendor/composer/../../app/Extensions/Servers/Enhance/Enhance.php): failed to open stream: No such file or directory at /var/www/paymenter/vendor/composer/ClassLoader.php:576)"}`

Also archive contains __MAC_OS related _junk_  hidden files :)

2. Additionally, when I attempted to open the "login product page," I encountered a "wrong token" error on the Enhance side. After logging out and logging back in, the error was resolved, and everything seemed fine. However, I am now unable to reproduce this error; everything is functioning correctly.

3.  Another point, slightly off-topic, but to assist the user in navigating directly to the specific order page without wandering around: What should be the parameter for `https://{site}/client/products/{id}`?

```blade
@component('mail::button', ['url' => route('clients.home')])
    View order
@endcomponent
```

**Comment by CorwinDev** [comment] 2024-02-26 16:05
1. Should be fixed
2. Weird, it might be expired
3. The route is clients.active-products.show and what emil template is it?

**Comment by Pachini** [comment] 2024-02-26 17:37
1. Ok now!
2. Maybe, anyway I can't reproduce it. Everything is fine
3. Email template is: NewOrder

Thank you for your work :)

**Comment by CorwinDev** [comment] 2024-02-26 17:51
I think you can do 
```blade
@component('mail::button', ['url' => route('clients.active-products.show', $products->first()->id)])
    View order
@endcomponent
```
I didn't test it tho!

_v1 will include this default :)_

**Comment by Pachini** [comment] 2024-02-26 18:33
Awesome, works as it should!

Where I can read about upcoming features in v1 release? :)

**Comment by CorwinDev** [comment] 2024-02-26 18:42
We don't have a exact feature list yet, but i can give you some sneakpeeks on our discord https://discord.gg/xB4UUT3XQg (corwindev for dms)

**Closed as completed by CorwinDev** 2024-02-26 18:42 UTC
